# Generated by Django 2.0.3 on 2018-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
