# Generated by Django 2.0.3 on 2018-03-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermostat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thermostat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
